version: "3.7"

services:
  litlcity:
    container_name: litlcity
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JEKYLL_ENV=production
    ports:
      - "55901:4000"
    entrypoint: ["sh", "-c"]
    command:
      - |
        bundle install
        jekyll build
        jekyll serve --watch --host 0.0.0.0
