version: "3.7"

services:
  litlcity:
    container_name: litlcity
    platform: linux/amd64
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/srv/jekyll
    ports:
      - "55901:4000"
    entrypoint: ["sh", "-c"]
    command:
      - |
        bundle install
        jekyll serve --watch --host 0.0.0.0
